In [1]:
import pandas as pd
import numpy as np

df = pd.ExcelFile('COVID-19-Constructed-Dataset-(PANEL).xlsx').parse('Sheet1')
school=[]
school.append(df['school'])

school = np.array(school)
print(school)
print(school.shape)
print(school[0])

school = school[0]
print(school)

[[0 0 0 ... 1 1 1]]
(1, 8400)
[0 0 0 ... 1 1 1]
[0 0 0 ... 1 1 1]


In [2]:
covidpos = []
covidpos.append(df['covidpos'])

covidpos = np.array(covidpos)
print(covidpos)

covidpos = covidpos[0]
print(covidpos)

[[1 1 1 ... 1 1 1]]
[1 1 1 ... 1 1 1]


In [3]:
# load readingscore, writingscore, mathscore, readingscoreSL, writingscoreSL, mathscoreSL

readingscore = []
readingscore.append(df['readingscore'])
readingscore = np.array(readingscore)
readingscore = readingscore[0]

writingscore = []
writingscore.append(df['writingscore'])
writingscore = np.array(writingscore)
writingscore = writingscore[0]

mathscore = []
mathscore.append(df['mathscore'])
mathscore = np.array(mathscore)
mathscore = mathscore[0]


readingscoreSL = [] 
readingscoreSL.append(df['readingscoreSL'])
readingscoreSL = np.array(readingscoreSL)
readingscoreSL = readingscoreSL[0]

writingscoreSL = []
writingscoreSL.append(df['writingscoreSL'])
writingscoreSL = np.array(writingscoreSL)
writingscoreSL = writingscoreSL[0]

mathscoreSL = []
mathscoreSL.append(df['mathscoreSL'])
mathscoreSL = np.array(mathscoreSL)
mathscoreSL = mathscoreSL[0]

In [10]:
import statistics
from scipy.stats import t


school0_readingscores = []
school1_readingscores = [] 

for i in range(len(readingscore)):
    if school[i] == 0:
        school0_readingscores.append(readingscore[i])
    else:
        school1_readingscores.append(readingscore[i])
        
# print(len(school0_readingscores))
# print(len(school1_readingscores))
print(f'Average reading score: {statistics.mean(readingscore)}')
print('READING SCORE')
print(f'school 0 - mean reading score: {statistics.mean(school0_readingscores)} - variance: {statistics.variance(school0_readingscores)}')
print(f'school 1 - mean reading score: {statistics.mean(school1_readingscores)} - variance: {statistics.variance(school1_readingscores)}')


mean_school0 = statistics.mean(school0_readingscores)
mean_school1 = statistics.mean(school1_readingscores)
var_school0 = statistics.variance(school0_readingscores)
var_school1 = statistics.variance(school1_readingscores)
n_school0 = len(school0_readingscores)
n_school1 = len(school1_readingscores)


t_value = (mean_school0 - mean_school1) / np.sqrt((var_school0 / n_school0) + (var_school1 / n_school1))

df = ((var_school0 / n_school0) + (var_school1 / n_school1))**2 / (((var_school0 / n_school0)**2 / (n_school0 - 1)) + ((var_school1 / n_school1)**2 / (n_school1 - 1)))

# Calculate the two-tailed p-value
p_value = t.sf(np.abs(t_value), df) * 2

print(f'T-value: {t_value}')
print(f'Degrees of freedom: {df}')
print(f'P-value: {p_value}')


Average reading score: 73.85305449985323
READING SCORE
school 0 - mean reading score: 80.57048085712252 - variance: 110.60089600385163
school 1 - mean reading score: 67.13562814258394 - variance: 152.7013366717343
T-value: 53.65748143579656
Degrees of freedom: 8188.648334460586
P-value: 0.0


In [17]:
school0_writingscores = []
school1_writingscores = [] 

for i in range(len(writingscore)):
    if school[i] == 0:
        school0_writingscores.append(writingscore[i])
    else:
        school1_writingscores.append(writingscore[i])
        
# print(len(school0_readingscores))
# print(len(school1_readingscores))
print(f'Average writing score: {statistics.mean(writingscore)}')
print('WRITING SCORE')
print(f'school 0 - mean writing score: {statistics.mean(school0_writingscores)} - variance: {statistics.variance(school0_writingscores)}')
print(f'school 1 - mean writing score: {statistics.mean(school1_writingscores)} - variance: {statistics.variance(school1_writingscores)}')


mean_school0 = statistics.mean(school0_writingscores)
mean_school1 = statistics.mean(school1_writingscores)
var_school0 = statistics.variance(school0_writingscores)
var_school1 = statistics.variance(school1_writingscores)
n_school0 = len(school0_writingscores)
n_school1 = len(school1_writingscores)


t_value = (mean_school0 - mean_school1) / np.sqrt((var_school0 / n_school0) + (var_school1 / n_school1))

df = ((var_school0 / n_school0) + (var_school1 / n_school1))**2 / (((var_school0 / n_school0)**2 / (n_school0 - 1)) + ((var_school1 / n_school1)**2 / (n_school1 - 1)))

# Calculate the two-tailed p-value
p_value = t.sf(np.abs(t_value), df) * 2

print(f'T-value: {t_value}')
print(f'Degrees of freedom: {df}')
print(f'P-value: {p_value}')

Average writing score: 76.44221496990748
WRITING SCORE
school 0 - mean reading score: 83.13902367546444 - variance: 127.62048777813126
school 1 - mean reading score: 69.74540626435052 - variance: 183.87698180051558
T-value: 49.18076420424364
Degrees of freedom: 8132.739170328485
P-value: 0.0


In [18]:
school0_mathscores = []
school1_mathscores = [] 

for i in range(len(mathscore)):
    if school[i] == 0:
        school0_mathscores.append(mathscore[i])
    else:
        school1_mathscores.append(mathscore[i])
        
# print(len(school0_readingscores))
# print(len(school1_readingscores))
print(f'Average math score: {statistics.mean(mathscore)}')
print('MATH SCORE')
print(f'school 0 - mean math score: {statistics.mean(school0_mathscores)} - variance: {statistics.variance(school0_mathscores)}')
print(f'school 1 - mean math score: {statistics.mean(school1_mathscores)} - variance: {statistics.variance(school1_mathscores)}')


mean_school0 = statistics.mean(school0_mathscores)
mean_school1 = statistics.mean(school1_mathscores)
var_school0 = statistics.variance(school0_mathscores)
var_school1 = statistics.variance(school1_mathscores)
n_school0 = len(school0_mathscores)
n_school1 = len(school1_mathscores)


t_value = (mean_school0 - mean_school1) / np.sqrt((var_school0 / n_school0) + (var_school1 / n_school1))

df = ((var_school0 / n_school0) + (var_school1 / n_school1))**2 / (((var_school0 / n_school0)**2 / (n_school0 - 1)) + ((var_school1 / n_school1)**2 / (n_school1 - 1)))

# Calculate the two-tailed p-value
p_value = t.sf(np.abs(t_value), df) * 2

print(f'T-value: {t_value}')
print(f'Degrees of freedom: {df}')
print(f'P-value: {p_value}')

Average math score: 74.68687063217163
MATH SCORE
school 0 - mean reading score: 79.70328744161696 - variance: 124.5320118739117
school 1 - mean reading score: 69.6704538227263 - variance: 177.95399687681035
T-value: 37.38484716801382
Degrees of freedom: 8143.98099493463
P-value: 1.871643181930285e-282


In [16]:
school0_readingscoresSL = []
school1_readingscoresSL = [] 

for i in range(len(readingscoreSL)):
    if school[i] == 0:
        school0_readingscoresSL.append(readingscoreSL[i])
    else:
        school1_readingscoresSL.append(readingscoreSL[i])
        
# print(len(school0_readingscores))
# print(len(school1_readingscores))
print(f'Average reading score SL: {statistics.mean(readingscoreSL)}')
print('READING SCORE SL')
print(f'school 0 - mean reading SL score: {statistics.mean(school0_readingscoresSL)} - variance: {statistics.variance(school0_readingscoresSL)}')
print(f'school 1 - mean reading SL score: {statistics.mean(school1_readingscoresSL)} - variance: {statistics.variance(school1_readingscoresSL)}')


mean_school0 = statistics.mean(school0_readingscoresSL)
mean_school1 = statistics.mean(school1_readingscoresSL)
var_school0 = statistics.variance(school0_readingscoresSL)
var_school1 = statistics.variance(school1_readingscoresSL)
n_school0 = len(school0_readingscoresSL)
n_school1 = len(school1_readingscoresSL)


t_value = (mean_school0 - mean_school1) / np.sqrt((var_school0 / n_school0) + (var_school1 / n_school1))

df = ((var_school0 / n_school0) + (var_school1 / n_school1))**2 / (((var_school0 / n_school0)**2 / (n_school0 - 1)) + ((var_school1 / n_school1)**2 / (n_school1 - 1)))

# Calculate the two-tailed p-value
p_value = t.sf(np.abs(t_value), df) * 2

print(f'T-value: {t_value}')
print(f'Degrees of freedom: {df}')
print(f'P-value: {p_value}')


Average reading score SL: 70.8286707687378
READING SCORE SL
school 0 - mean reading score: 76.82235536938622 - variance: 135.32823522015318
school 1 - mean reading score: 64.83498616808937 - variance: 152.47072000288756
T-value: 45.793508667016525
Degrees of freedom: 8368.310226051193
P-value: 0.0


In [19]:
school0_writingscoresSL = []
school1_writingscoresSL = [] 

for i in range(len(writingscoreSL)):
    if school[i] == 0:
        school0_writingscoresSL.append(writingscoreSL[i])
    else:
        school1_writingscoresSL.append(writingscoreSL[i])
        
# print(len(school0_readingscores))
# print(len(school1_readingscores))
print(f'Average writing SL score: {statistics.mean(writingscoreSL)}')
print('WRITING SL SCORE')
print(f'school 0 - mean writing SL score: {statistics.mean(school0_writingscoresSL)} - variance: {statistics.variance(school0_writingscoresSL)}')
print(f'school 1 - mean writing SL score: {statistics.mean(school1_writingscoresSL)} - variance: {statistics.variance(school1_writingscoresSL)}')


mean_school0 = statistics.mean(school0_writingscoresSL)
mean_school1 = statistics.mean(school1_writingscoresSL)
var_school0 = statistics.variance(school0_writingscoresSL)
var_school1 = statistics.variance(school1_writingscoresSL)
n_school0 = len(school0_writingscoresSL)
n_school1 = len(school1_writingscoresSL)


t_value = (mean_school0 - mean_school1) / np.sqrt((var_school0 / n_school0) + (var_school1 / n_school1))

df = ((var_school0 / n_school0) + (var_school1 / n_school1))**2 / (((var_school0 / n_school0)**2 / (n_school0 - 1)) + ((var_school1 / n_school1)**2 / (n_school1 - 1)))

# Calculate the two-tailed p-value
p_value = t.sf(np.abs(t_value), df) * 2

print(f'T-value: {t_value}')
print(f'Degrees of freedom: {df}')
print(f'P-value: {p_value}')

Average writing SL score: 72.82170442944481
WRITING SL SCORE
school 0 - mean reading score: 78.19871687662034 - variance: 115.59135940918753
school 1 - mean reading score: 67.44469198226929 - variance: 181.60582539148996
T-value: 40.4271696580138
Degrees of freedom: 8003.134697868451
P-value: 0.0


In [20]:
school0_mathscoresSL = []
school1_mathscoresSL = [] 

for i in range(len(mathscoreSL)):
    if school[i] == 0:
        school0_mathscoresSL.append(mathscoreSL[i])
    else:
        school1_mathscoresSL.append(mathscoreSL[i])
        
# print(len(school0_readingscores))
# print(len(school1_readingscores))
print(f'Average math SL score: {statistics.mean(mathscoreSL)}')
print('MATH SL SCORE')
print(f'school 0 - mean math SL score: {statistics.mean(school0_mathscoresSL)} - variance: {statistics.variance(school0_mathscoresSL)}')
print(f'school 1 - mean math SL score: {statistics.mean(school1_mathscoresSL)} - variance: {statistics.variance(school1_mathscoresSL)}')


mean_school0 = statistics.mean(school0_mathscoresSL)
mean_school1 = statistics.mean(school1_mathscoresSL)
var_school0 = statistics.variance(school0_mathscoresSL)
var_school1 = statistics.variance(school1_mathscoresSL)
n_school0 = len(school0_mathscoresSL)
n_school1 = len(school1_mathscoresSL)


t_value = (mean_school0 - mean_school1) / np.sqrt((var_school0 / n_school0) + (var_school1 / n_school1))

df = ((var_school0 / n_school0) + (var_school1 / n_school1))**2 / (((var_school0 / n_school0)**2 / (n_school0 - 1)) + ((var_school1 / n_school1)**2 / (n_school1 - 1)))

# Calculate the two-tailed p-value
p_value = t.sf(np.abs(t_value), df) * 2

print(f'T-value: {t_value}')
print(f'Degrees of freedom: {df}')
print(f'P-value: {p_value}')

Average math SL score: 71.444913788523
MATH SL SCORE
school 0 - mean reading score: 75.51498056093851 - variance: 152.28905045873336
school 1 - mean reading score: 67.37484701610747 - variance: 180.65743393676615
T-value: 28.911389078325843
Degrees of freedom: 8337.472224781375
P-value: 3.0705466526872387e-175


# covidpos

In [22]:
covidpos0_readingscores = []
covidpos1_readingscores = [] 

for i in range(len(readingscore)):
    if covidpos[i] == 0:
        covidpos0_readingscores.append(readingscore[i])
    else:
        covidpos1_readingscores.append(readingscore[i])
        
# print(len(school0_readingscores))
# print(len(school1_readingscores))
print(f'Average reading score: {statistics.mean(readingscore)}')
print('READING SCORE')
print(f'covidpos 0 - mean reading score: {statistics.mean(covidpos0_readingscores)} - variance: {statistics.variance(covidpos0_readingscores)}')
print(f'covidpos 1 - mean reading score: {statistics.mean(covidpos1_readingscores)} - variance: {statistics.variance(covidpos1_readingscores)}')


mean_school0 = statistics.mean(covidpos0_readingscores)
mean_school1 = statistics.mean(covidpos1_readingscores)
var_school0 = statistics.variance(covidpos0_readingscores)
var_school1 = statistics.variance(covidpos1_readingscores)
n_school0 = len(covidpos0_readingscores)
n_school1 = len(covidpos1_readingscores)


t_value = (mean_school0 - mean_school1) / np.sqrt((var_school0 / n_school0) + (var_school1 / n_school1))

df = ((var_school0 / n_school0) + (var_school1 / n_school1))**2 / (((var_school0 / n_school0)**2 / (n_school0 - 1)) + ((var_school1 / n_school1)**2 / (n_school1 - 1)))

# Calculate the two-tailed p-value
p_value = t.sf(np.abs(t_value), df) * 2

print(f'T-value: {t_value}')
print(f'Degrees of freedom: {df}')
print(f'P-value: {p_value}')

Average reading score: 73.85305449985323
READING SCORE
covidpos 0 - mean reading score: 76.29340223980765 - variance: 163.17981068522118
covidpos 1 - mean reading score: 68.93028405891067 - variance: 167.97700942479182
T-value: 24.626942258594298
Degrees of freedom: 5479.041626419748
P-value: 4.244403706121011e-127


In [26]:
covidpos0_writingscores = []
covidpos1_writingscores = [] 

for i in range(len(writingscore)):
    if covidpos[i] == 0:
        covidpos0_writingscores.append(writingscore[i])
    else:
        covidpos1_writingscores.append(writingscore[i])
        
# print(len(school0_readingscores))
# print(len(school1_readingscores))
print(f'Average writing score: {statistics.mean(writingscore)}')
print('WRITING SCORE')
print(f'covidpos 0 - mean writing score: {statistics.mean(covidpos0_writingscores)} - variance: {statistics.variance(covidpos0_writingscores)}')
print(f'covidpos 1 - mean writing score: {statistics.mean(covidpos1_writingscores)} - variance: {statistics.variance(covidpos1_writingscores)}')


mean_school0 = statistics.mean(covidpos0_writingscores)
mean_school1 = statistics.mean(covidpos1_writingscores)
var_school0 = statistics.variance(covidpos0_writingscores)
var_school1 = statistics.variance(covidpos1_writingscores)
n_school0 = len(covidpos0_writingscores)
n_school1 = len(covidpos1_writingscores)


t_value = (mean_school0 - mean_school1) / np.sqrt((var_school0 / n_school0) + (var_school1 / n_school1))

df = ((var_school0 / n_school0) + (var_school1 / n_school1))**2 / (((var_school0 / n_school0)**2 / (n_school0 - 1)) + ((var_school1 / n_school1)**2 / (n_school1 - 1)))

# Calculate the two-tailed p-value
p_value = t.sf(np.abs(t_value), df) * 2

print(f'T-value: {t_value}')
print(f'Degrees of freedom: {df}')
print(f'P-value: {p_value}')

Average writing score: 76.44221496990748
WRITING SCORE
covidpos 0 - mean writing score: 78.82285629853904 - variance: 182.47717724897532
covidpos 1 - mean writing score: 71.63988677249557 - variance: 202.67746378670603
T-value: 22.13624160903425
Degrees of freedom: 5298.46275788673
P-value: 6.406892835303732e-104


In [24]:
covidpos0_mathscores = []
covidpos1_mathscores = [] 

for i in range(len(mathscore)):
    if covidpos[i] == 0:
        covidpos0_mathscores.append(mathscore[i])
    else:
        covidpos1_mathscores.append(mathscore[i])
        
# print(len(school0_readingscores))
# print(len(school1_readingscores))
print(f'Average math score: {statistics.mean(mathscore)}')
print('math SCORE')
print(f'covidpos 0 - mean math score: {statistics.mean(covidpos0_mathscores)} - variance: {statistics.variance(covidpos0_mathscores)}')
print(f'covidpos 1 - mean math score: {statistics.mean(covidpos1_mathscores)} - variance: {statistics.variance(covidpos1_mathscores)}')


mean_school0 = statistics.mean(covidpos0_mathscores)
mean_school1 = statistics.mean(covidpos1_mathscores)
var_school0 = statistics.variance(covidpos0_mathscores)
var_school1 = statistics.variance(covidpos1_mathscores)
n_school0 = len(covidpos0_mathscores)
n_school1 = len(covidpos1_mathscores)


t_value = (mean_school0 - mean_school1) / np.sqrt((var_school0 / n_school0) + (var_school1 / n_school1))

df = ((var_school0 / n_school0) + (var_school1 / n_school1))**2 / (((var_school0 / n_school0)**2 / (n_school0 - 1)) + ((var_school1 / n_school1)**2 / (n_school1 - 1)))

# Calculate the two-tailed p-value
p_value = t.sf(np.abs(t_value), df) * 2

print(f'T-value: {t_value}')
print(f'Degrees of freedom: {df}')
print(f'P-value: {p_value}')

Average math score: 74.68687063217163
math SCORE
covidpos 0 - mean math score: 76.59427307406042 - variance: 160.39846349160993
covidpos 1 - mean math score: 70.83917949939597 - variance: 186.57357249255293
T-value: 18.615508260329825
Degrees of freedom: 5193.093955657708
P-value: 6.303362515052586e-75


In [25]:
covidpos0_readingscoresSL = []
covidpos1_readingscoresSL = [] 

for i in range(len(readingscoreSL)):
    if covidpos[i] == 0:
        covidpos0_readingscoresSL.append(readingscoreSL[i])
    else:
        covidpos1_readingscoresSL.append(readingscoreSL[i])
        
# print(len(school0_readingscores))
# print(len(school1_readingscores))
print(f'Average reading SL score: {statistics.mean(readingscoreSL)}')
print('READING SL SCORE')
print(f'covidpos 0 - mean reading SL score: {statistics.mean(covidpos0_readingscoresSL)} - variance: {statistics.variance(covidpos0_readingscoresSL)}')
print(f'covidpos 1 - mean reading SL score: {statistics.mean(covidpos1_readingscoresSL)} - variance: {statistics.variance(covidpos1_readingscoresSL)}')


mean_school0 = statistics.mean(covidpos0_readingscoresSL)
mean_school1 = statistics.mean(covidpos1_readingscoresSL)
var_school0 = statistics.variance(covidpos0_readingscoresSL)
var_school1 = statistics.variance(covidpos1_readingscoresSL)
n_school0 = len(covidpos0_readingscoresSL)
n_school1 = len(covidpos1_readingscoresSL)


t_value = (mean_school0 - mean_school1) / np.sqrt((var_school0 / n_school0) + (var_school1 / n_school1))

df = ((var_school0 / n_school0) + (var_school1 / n_school1))**2 / (((var_school0 / n_school0)**2 / (n_school0 - 1)) + ((var_school1 / n_school1)**2 / (n_school1 - 1)))

# Calculate the two-tailed p-value
p_value = t.sf(np.abs(t_value), df) * 2

print(f'T-value: {t_value}')
print(f'Degrees of freedom: {df}')
print(f'P-value: {p_value}')

Average reading SL score: 70.8286707687378
READING SL SCORE
covidpos 0 - mean reading SL score: 73.32455008525794 - variance: 166.97359507427018
covidpos 1 - mean reading SL score: 65.79387973368853 - variance: 167.84710047816935
T-value: 25.09921270209786
Degrees of freedom: 5537.228490675688
P-value: 9.252126007171756e-132


In [27]:
covidpos0_writingscoresSL = []
covidpos1_writingscoresSL = [] 

for i in range(len(writingscoreSL)):
    if covidpos[i] == 0:
        covidpos0_writingscoresSL.append(writingscoreSL[i])
    else:
        covidpos1_writingscoresSL.append(writingscoreSL[i])
        
# print(len(school0_readingscores))
# print(len(school1_readingscores))
print(f'Average writing SL score: {statistics.mean(writingscoreSL)}')
print('WRITING SL SCORE')
print(f'covidpos 0 - mean writing SL score: {statistics.mean(covidpos0_writingscoresSL)} - variance: {statistics.variance(covidpos0_writingscoresSL)}')
print(f'covidpos 1 - mean writing SL score: {statistics.mean(covidpos1_writingscoresSL)} - variance: {statistics.variance(covidpos1_writingscoresSL)}')


mean_school0 = statistics.mean(covidpos0_writingscoresSL)
mean_school1 = statistics.mean(covidpos1_writingscoresSL)
var_school0 = statistics.variance(covidpos0_writingscoresSL)
var_school1 = statistics.variance(covidpos1_writingscoresSL)
n_school0 = len(covidpos0_writingscoresSL)
n_school1 = len(covidpos1_writingscoresSL)


t_value = (mean_school0 - mean_school1) / np.sqrt((var_school0 / n_school0) + (var_school1 / n_school1))

df = ((var_school0 / n_school0) + (var_school1 / n_school1))**2 / (((var_school0 / n_school0)**2 / (n_school0 - 1)) + ((var_school1 / n_school1)**2 / (n_school1 - 1)))

# Calculate the two-tailed p-value
p_value = t.sf(np.abs(t_value), df) * 2

print(f'T-value: {t_value}')
print(f'Degrees of freedom: {df}')
print(f'P-value: {p_value}')

Average writing SL score: 72.82170442944481
WRITING SL SCORE
covidpos 0 - mean writing SL score: 75.20245805628959 - variance: 157.2454839175313
covidpos 1 - mean writing SL score: 68.01914969943036 - variance: 183.9085584660879
T-value: 23.422061373478797
Degrees of freedom: 5180.841511056809
P-value: 2.1004641016960147e-115


In [28]:
covidpos0_mathscoresSL = []
covidpos1_mathscoresSL = [] 

for i in range(len(mathscoreSL)):
    if covidpos[i] == 0:
        covidpos0_mathscoresSL.append(mathscoreSL[i])
    else:
        covidpos1_mathscoresSL.append(mathscoreSL[i])
        
# print(len(school0_readingscores))
# print(len(school1_readingscores))
print(f'Average math SL core: {statistics.mean(mathscoreSL)}')
print('MATH SL SCORE')
print(f'covidpos 0 - mean math SL score: {statistics.mean(covidpos0_mathscoresSL)} - variance: {statistics.variance(covidpos0_mathscoresSL)}')
print(f'covidpos 1 - mean math SL score: {statistics.mean(covidpos1_mathscoresSL)} - variance: {statistics.variance(covidpos1_mathscoresSL)}')


mean_school0 = statistics.mean(covidpos0_mathscoresSL)
mean_school1 = statistics.mean(covidpos1_mathscoresSL)
var_school0 = statistics.variance(covidpos0_mathscoresSL)
var_school1 = statistics.variance(covidpos1_mathscoresSL)
n_school0 = len(covidpos0_mathscoresSL)
n_school1 = len(covidpos1_mathscoresSL)


t_value = (mean_school0 - mean_school1) / np.sqrt((var_school0 / n_school0) + (var_school1 / n_school1))

df = ((var_school0 / n_school0) + (var_school1 / n_school1))**2 / (((var_school0 / n_school0)**2 / (n_school0 - 1)) + ((var_school1 / n_school1)**2 / (n_school1 - 1)))

# Calculate the two-tailed p-value
p_value = t.sf(np.abs(t_value), df) * 2

print(f'T-value: {t_value}')
print(f'Degrees of freedom: {df}')
print(f'P-value: {p_value}')

Average math SL core: 71.444913788523
MATH SL SCORE
covidpos 0 - mean math SL score: 73.44192079770939 - variance: 169.78576431476023
covidpos 1 - mean math SL score: 67.41646861481941 - variance: 185.50785042550578
T-value: 19.359930475661216
Degrees of freedom: 5336.755099165695
P-value: 9.357900978504736e-81
